name: mikropix-frontend
type: static
source:
  type: github
  repository: https://github.com/SEU_USUARIO/mikropix-frontend
  branch: main
build:
  command: npm run build
  output: dist
  node_version: "18"
env:
  VITE_API_URL: https://api.mikropix.online
  VITE_SUPABASE_URL: https://zzfugxcsinasxrhcwvcp.supabase.co
  VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6ZnVneGNzaW5hc3hyaGN3dmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODIwNTEsImV4cCI6MjA2NTc1ODA1MX0.xHJzQC_tzWxdcGYw-WzYOFaKUkUb3HdlIr2EcWM4diw
  VITE_APP_NAME: MikroPIX
  VITE_APP_VERSION: 2.1.5
  VITE_MODE: production
  NODE_ENV: production
domain:
  - mikropix.online
  - www.mikropix.online
redirect:
  - from: www.mikropix.online
    to: mikropix.online